--- # Python environment installation tasks

- name: install python requirements
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libreadline6-dev 
    - libbz2-dev 
    - libssl-dev 
    - libsqlite3-dev 
    - libncursesw5-dev 
    - libffi-dev 
    - libdb-dev 
    - libexpat1-dev 
    - zlib1g-dev 
    - liblzma-dev 
    - libgdbm-dev 
    - libffi-dev 
    - libmpdec-dev
    - libldap2-dev
    - libsasl2-dev
    - python-dev
    - python-pip

- name: pip install pew
  pip:
    name: pew
    state: latest

- name: pip install cookiecutter
  pip:
    name: cookiecutter
    state: latest

- name: install python versions
  command: "pew install {{ item }}"
  become: true
  become_user: vagrant
  with_items:
    "{{ python_versions|default([]) }}"
